### ISSUE TITLE
Cannot create two instances of NettyClient

### ISSUE THREAD

**Issue by heychirag** [spotware/ctrader-open-api-v2-java-example#13]
**Describe the bug**
I am unable to create to two instances of NettyClient as I need to Authorise a Live and a Demo account in the same application.

**To Reproduce**
Try initialising two instances of NettyClient.

**Expected behavior**
We should be able to create as many instances of NettyClient as we want.

**Log files**
```
2020-08-15 19:23:40 WARN  ChannelInitializer:97 - Failed to initialize a channel. Closing: [id: 0x75c8ff27]
io.netty.channel.ChannelPipelineException: com.spotware.connect.netty.handler.HeartbeatOnIdleHandler is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:604)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
	at com.spotware.connect.netty.NettyClient.initPipelineForChannel(NettyClient.java:109)
	at com.spotware.connect.netty.NettyClient.access$000(NettyClient.java:38)
	at com.spotware.connect.netty.NettyClient$1.initChannel(NettyClient.java:83)
	at com.spotware.connect.netty.NettyClient$1.initChannel(NettyClient.java:80)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:613)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1475)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1127)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:654)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
**Additional context**

**Comment by LeoSko** [comment]
This is an **example** repo, not ready-to-use library or framework. If you want to create two NettyClient instances, you must make some modifications to the code and this is expected.

**Comment by heychirag** [comment]
@LeoSko What would happen if I make the handle Shareable? Are there any consequences to it?

**Comment by LeoSko** [comment]
@heychirag, you need to google it, welcome to development. :)
